//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: savestate.proto
// Note: requires additional types generated from: referee.proto
namespace SSLRig.Core.Data.Packet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SaveState")]
  public partial class SaveState : global::ProtoBuf.IExtensible
  {
    public SaveState() {}
    
    private SSL_Referee _referee;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"referee", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public SSL_Referee referee
    {
      get { return _referee; }
      set { _referee = value; }
    }
    private uint _yellow_penalty_goals;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"yellow_penalty_goals", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint yellow_penalty_goals
    {
      get { return _yellow_penalty_goals; }
      set { _yellow_penalty_goals = value; }
    }
    private uint _blue_penalty_goals;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"blue_penalty_goals", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint blue_penalty_goals
    {
      get { return _blue_penalty_goals; }
      set { _blue_penalty_goals = value; }
    }
    private ulong _time_taken;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"time_taken", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong time_taken
    {
      get { return _time_taken; }
      set { _time_taken = value; }
    }

    private SaveState.CardInfo _last_card = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"last_card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SaveState.CardInfo last_card
    {
      get { return _last_card; }
      set { _last_card = value; }
    }

    private SaveState.TimeoutInfo _timeout = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"timeout", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SaveState.TimeoutInfo timeout
    {
      get { return _timeout; }
      set { _timeout = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardInfo")]
  public partial class CardInfo : global::ProtoBuf.IExtensible
  {
    public CardInfo() {}
    
    private SaveState.Team _team;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public SaveState.Team team
    {
      get { return _team; }
      set { _team = value; }
    }
    private SaveState.Card _card;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public SaveState.Card card
    {
      get { return _card; }
      set { _card = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimeoutInfo")]
  public partial class TimeoutInfo : global::ProtoBuf.IExtensible
  {
    public TimeoutInfo() {}
    
    private SaveState.Team _team;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public SaveState.Team team
    {
      get { return _team; }
      set { _team = value; }
    }
    private uint _left_before;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"left_before", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint left_before
    {
      get { return _left_before; }
      set { _left_before = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Team")]
    public enum Team
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM_YELLOW", Value=0)]
      TEAM_YELLOW = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM_BLUE", Value=1)]
      TEAM_BLUE = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Card")]
    public enum Card
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CARD_YELLOW", Value=0)]
      CARD_YELLOW = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CARD_RED", Value=1)]
      CARD_RED = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
